on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update
        run: python3 generate.py >version.txt
      - name: commit
        run: git commit --author "GitHub <noreply@github.com>" -a -m "Update to 1.3.`cat version.txt`""
        continue-on-error: true
      - name: create pr
        uses: peter-evans/create-pull-request@v4
